### ISSUE TITLE
colored frame no longer appears

### ISSUE THREAD

**Issue by pocki80** [fsantini/amazon-delivercheck-addon#1]
I am using Firefox 66.0.3 64bit Windows and since some time ago I am missing the red/yellow/green frames surrounding the search results.

When using www.amazon.de and being logged in wiht a default delivery address to Austria, the sear results look like this:
![image](https://user-images.githubusercontent.com/16037544/56193732-a1756480-6031-11e9-90fc-cf872b099d58.png)

**Comment by fsantini** [comment]
Hi! Thanks for raising the issue! The amazon website changed and it should be fixed now. I just pushed the modification, it will take some time until it appears onin the firefox addon site.
